name: Android CI

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Access PROPERTIES_URL
      env:
        PROPERTIES_URL: ${{ secrets.PROPERTIES_URL }}
      run: echo PROPERTIES_URL=\"$PROPERTIES_URL\" > ./local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app
        path: app/build/outputs/apk
