name: Android CI

on:
#   workflow_dispatch:
 push:
   branches: [ "dev", "main" ]
 pull_request:
   branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle        
    - name: Access Secret and Write to properties
      env:
        STOREFILE: ${{ secrets.STOREFILE }}
        STOREPASSWORD: ${{ secrets.STOREPASSWORD }}
        KEYALIAS: ${{ secrets.KEYALIAS }}
        KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
      run: |
        echo -e "\nSTOREFILE=$STOREFILE" >> local.properties
        echo -e "\nSTOREPASSWORD=$STOREPASSWORD" >> local.properties
        echo -e "\nKEYALIAS=$KEYALIAS" >> local.properties
        echo -e "\nKEYPASSWORD=$KEYPASSWORD" >> local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Assemble Release Bundle
      run: |
          ./gradlew bundleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app
        path: app/build/outputs/bundle
