name: Android CI

on:
#   workflow_dispatch:
 push:
   branches: [ "dev", "main" ]
 pull_request:
   branches: [ "dev", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked:  "
        echo ${{ secrets.STOREFILE }}
        echo "Trick to echo GitHub Actions Secret:  "
        echo ${{secrets.STOREFILE}} | sed 's/./& /g' 
        echo ${{secrets.STOREPASSWORD}} | sed 's/./& /g'         
        echo ${{secrets.KEYALIAS}} | sed 's/./& /g' 
        echo ${{secrets.KEYPASSWORD}} | sed 's/./& /g' 
        
#     - name: Access STOREFILE
#       env:
#         STOREFILE: ${{ secrets.STOREFILE }}
#         STOREPASSWORD: ${{ secrets.STOREPASSWORD }}
#         KEYALIAS: ${{ secrets.KEYALIAS }}
#         KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
#       run: echo $STOREFILE 
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build
#     - name: Assemble Release Bundle
#       run: |
#           ./gradlew bundleRelease
#     - name: Upload APK
#       uses: actions/upload-artifact@v3.1.0
#       with:
#         name: app
#         path: app/build/outputs/bundle
